var num1 = 10;
var num2 = 4;
var result1 = num1 + num2;
console.log(result1);
var result2 = num1 - num2;
console.log(result2);
var result3 = num1 / num2;
console.log(result3);
var result4 = num1 * num2;
console.log(result4);
var result5 = num1 % num2;
console.log(result5);
var result6 = Math.pow(num1, num2);
console.log(result6);
var a = 5;
var b = "5";
var result7 = a == b;
console.log(result7);
var c = 5;
var d = "5";
var result8 = c === d;
console.log(result8);
var result9 = a != b;
console.log(result9);
var result10 = a !== b;
console.log(result10);
console.log(num1 < num2);
console.log(num1 > num2);
