var students = ["Owais", "Rehan", "Ali", "Asad"];
console.log(students);
console.log(students[0]);
console.log(students[2]);
var teacher = ["Owais", 1, "Rehan", 2];
console.log(teacher);
teacher[0] = "Ali";
teacher.push("Asad");
console.log(teacher);
teacher.pop();
console.log(teacher);
teacher.shift();
console.log(teacher);
